### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by jakesjews** [MindscapeHQ/ember-cli-raygun#10]
Would it be possible to get a new release published with the changes from https://github.com/MindscapeHQ/ember-cli-raygun/pull/4?

**Comment by chriskrycho** [comment]
Seconded, with a loud _please_!

**Comment by nikz** [comment]
@jakesjews @chriskrycho done!

**Comment by pixelhandler** [comment]
@nikz cc\ @jakesjews @chriskrycho See #11, was the 1.2.0 release published to NPM?
