### ISSUE TITLE
Switch to/support distributing via npm

### ISSUE THREAD

**Issue by chriskrycho** [MindscapeHQ/ember-cli-raygun#15]
A few reasons:

- The Ember ecosystem is rapidly moving away from the use of Bower
- Bower itself is deprecated:
    > ...psst! While Bower is maintained, we recommend yarn and webpack for new front-end projects!
- Raygun4js is available via npm

If you good folks would be so kind, we'd really appreciate it!

**Comment by nikz** [comment]
Hiya,

I can definitely look into this, although the PR shouldn't be too hard if you want to give it a go :)

Nik

**Comment by chriskrycho** [comment]
Thanks!

> although the PR shouldn't be too hard if you want to give it a go :)

If I had the time, I definitely would! Right now I'm swamped just trying to get [ember-cli-typescript] up to speed; what (very little) OSS time I have is allocated that way.

[ember-cli-typescript]: https://github.com/emberwatch/ember-cli-typescript

**Comment by joshjeppson** [comment]
This issue is closed, but running ember install ember-cli-raygun on a brand new ember app still uses bower. Is there something I'm missing?
