### ISSUE TITLE
Raygun doesnt detach

### ISSUE THREAD

**Issue by mono424** [MindscapeHQ/ember-cli-raygun#19]
If "enabled" changes in "env", there is an console statement, but Raygun is still active.

**Comment by nikz** [comment]
Hi @mono424 - this might be because Raygun4js is still loaded - are you still hitting this issue?

**Comment by mono424** [comment]
@nikz hey, no i did a hard switch to vuejs back then 😅

**Comment by nikz** [comment]
No problems! I'll close this for now.
