### ISSUE TITLE
Is this maintained?

### ISSUE THREAD

**Issue by chriskrycho** [MindscapeHQ/ember-cli-raygun#23]
As far as I see, there as been no maintainer activity since last August, including no publication of the changes that were merged then.

Is this addon maintained? If not, would you guys be up for a member of the community taking it over and maintaining it?

**Comment by nikz** [comment]
@chriskrycho hey! Thanks for getting in touch. I was planning to re-do this for Ember 3 - but you're more than welcome to take over if you'd like. I've just not had many active Ember projects for a while 😞

**Comment by chriskrycho** [comment]
Thanks!

I definitely have too much on my plate to take over maintenance personally – just wanted to see what status was! I’m trying to upgrade us to using the npm-based version and having issues, and wanted to make sure this still lived.

**Comment by nikz** [comment]
Alright - in that case, hang tight 😄 

(I'm going to close this issue now, but feel free to reach out to me if you'd like to chat any more)

**Comment by chriskrycho** [comment]
Sounds great! Please ping/announce/etc. when you have this ready to go. Among other things, I can help get TypeScript typings working correctly out of the box for TS consumers. 😄 Also, if you can make it use the V2 APIs while you're at it, that'd be great.

The only other thing I'll mention is: we have separate configs we use in different environments, which are bootstrapped into the app at boot time via payload, so we'd love it if that continued to work (i.e. not *requiring* setup in `environment.js` but supporting it at least in initializers).

**Comment by chriskrycho** [comment]
Hey @nikz, can we get an update on when you'll be working on this? It's our only blocker for finally removing Bower from our app entirely… which means it's also a blocker for our Ember 3.x upgrade, which we'd very much like to land in the next couple of weeks.
