### ISSUE TITLE
Upgrade to V2 Javscript API

### ISSUE THREAD

**Issue by jcypret** [MindscapeHQ/ember-cli-raygun#3]
This addon still uses the V1 api for interacting with Raygun. The docs recommend switching over to the new syntax: https://raygun.io/docs/languages/javascript#differences

I would be happy to open a pull request switching the add-on to the V2 syntax. Just let me know either way. Thanks!

**Comment by nikz** [comment]
Hi @jcypret - that sounds awesome, if you want to tackle that I'd be more than happy to help out :)

**Comment by CmdrKeen** [comment]
Likewise, the move to the V2 API wasn't as easy as we'd initially hoped for it to be. If you have any questions / issues, please post them on here and we'll have the team who work on Raygun4JS help out :) Thanks @jcypret!

**Comment by typeoneerror** [comment]
First pass here: https://github.com/MindscapeHQ/ember-cli-raygun/pull/5. Could use some help/thoughts.
