### ISSUE TITLE
Octane Support

### ISSUE THREAD

**Issue by joshjeppson** [MindscapeHQ/ember-cli-raygun#35]
This plugin appears to have last been updated prior to the release of Ember Octane. Does it work with Ember Octane? Are there plans to update it to Ember Octane and beyond?

**Comment by nikz** [comment]
@joshjeppson yep, apologies, it's quite out of date. I'm looking into it at the moment :)

**Comment by nikz** [comment]
@joshjeppson yep, apologies, it's quite out of date. I'm looking into it at the moment 👍

**Comment by joshjeppson** [comment]
Awesome, very much looking forward to a release, @nikz!

**Comment by joshjeppson** [comment]
Is there a release on the horizon?

**Comment by nikz** [comment]
@joshjeppson still working on, sorry for the wait.

**Comment by nikz** [comment]
@joshjeppson hot off the press, give: https://github.com/MindscapeHQ/ember-cli-raygun/tree/octane-beta a go.

Please treat this as very very beta (i.e not the google definition!)

**Comment by nikz** [comment]
@joshjeppson I've just published 2.0.0.beta.0 to npm - I'd be really keen on your feedback :)

**Comment by navels** [comment]
Any updates on this?  Thanks!

**Comment by navels** [comment]
Just received this letter from Raygun:

> I wanted to reach out to you as we have noticed your are still on an older version for Raygun4js for Crash Reporting and RUM and to urgently update to Raygun4Js v2.27.0.
> 
> This update changes the browser API's that we use to get RUM page timing information. This was done because the API we were using has become deprecated in some new browser versions which results in `NaN` values being collected for some timings.

I think we can just use an override to pull in the latest Raygun version but it would be nice to get some movement on this repo.  Is there anything I can do to help?

**Comment by redJ4y** [comment]
@navels Thank you for bringing this up. It appears that the provider is actually bringing in Raygun4JS from our CDN, meaning it will be using the latest version. The version you see in `package-lock.json` is unused (and should be removed). I suspect the letter you received from us was a false positive.

Regarding getting some movement on this repo, I totally agree. We have noted a couple of things to do, including getting rid of  the dependence on the deprecated `Ember.Logger`. Hopefully we can get that out soon!

**Comment by redJ4y** [comment]
@navels Scratch that. As you noted in your [Raygun Forum post](https://raygun.com/forums/thread/184406), it looks like the released package is out of date with the repo. Not sure how that happened, but I'll look into releasing a new version now.

**Comment by navels** [comment]
Thanks!

**Comment by redJ4y** [comment]
@navels In the meantime, please use version `2.0.0-beta.0`. [It is already up on npm](https://www.npmjs.com/package/ember-cli-raygun/v/2.0.0-beta.0).

**Comment by redJ4y** [comment]
I just put up version 2.0.0, sorry for the wait!
